version: '3'

services:
  client:
    build:
      context: ./client
    ports:
      - "6000:6000"
    environment:
      - PORT=6000
    networks:
      - shared

  server:
    build:
      context: ./server
    ports:
      - "1337:1337"
    environment:
      - PORT=1337
    networks:
      - shared

  logger:
    build:
      context: ./logger
    ports:
      - "1111:5000"
    environment:
      - PORT=5000
    networks:
      - shared

networks:
  shared: